
[env]
TERM = "alacritty"

[font]
size = 13

[font.bold]
family = "JetBrainsMono NF"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono NF"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono NF"
style = "Italic"

[font.normal]
family = "JetBrainsMono NF"
style = "Regular"

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "N"
mods = "Control|Shift"

[window]
dynamic_padding = true
dynamic_title = true
opacity = 0.9

[selection]
save_to_clipboard = true

[general]
import = ["~/.config/alacritty/catppuccin-mocha.toml"]

[window.padding]
x = 0
y = 0

[window.dimensions]
columns = 80
lines = 30
